### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by EdwinRozario** [mattThousand/sad_panda#3]
Hi Matt

   Do you mind me refactoring this gem a bit? I have forked it https://github.com/EdwinRozario/sad_panda. I dint know how to contact you and hence writing the message here.

**Comment by mattThousand** [comment]
Hi Edwin,

Of course, I am thrilled that you're interested in making a contribution! Just make a pull request to the main repo whenever you've put together something you'd like to be merged into the master branch 😄

**Comment by EdwinRozario** [comment]
Thanks Matt

I noticed that when calculating polarity the frequency of the word id being passed to the methods but never being used in the end result.

if polarity for 'codemonkey' = 1.1 and its used twice in a message, will the end result be 1.1 * 2?

**Comment by EdwinRozario** [comment]
@mattThousand I am afraid that my changes are a massive change in how the gem was written. It will be good if you can take a look at my work (https://github.com/EdwinRozario/sad_panda/tree/ed/refactoring) so far. And we can organise a chat if you want me to to take you through the changes.

**Comment by mattThousand** [comment]
Could you submit a pull request? That way we can see the diff and communicate on a single thread
